{inputs, ...}: {
  imports = [inputs.treefmt-nix.flakeModule];

  perSystem = {pkgs, ...}: {
    treefmt = {
      settings = {
        global.excludes = [".envrc"];

        formatter.biome = {
          command = pkgs.biome;
          options = [
            "format"
            "--write"
            "--indent-style=space"
          ];
          includes = ["*.js" "*.ts"];
          # Generated by wasm-bindgen into web/dist and copied into web/.
          excludes = ["web/space_game_client.d.ts"];
        };
      };

      programs = {
        # keep-sorted start
        alejandra.enable = true;
        deadnix.enable = true;
        nixf-diagnose.enable = true;
        statix.enable = true;
        # keep-sorted end

        # keep-sorted start
        keep-sorted.enable = true;
        rustfmt.enable = true;
        taplo.enable = true;
        # keep-sorted end
      };
    };
  };
}
