[package]
name = "space-game-client"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
default = []
browser-dev = []
dev = ["bevy/dynamic_linking", "avian2d/debug-plugin"]

[dependencies]
avian2d.workspace = true
bevy = { workspace = true, features = [
  # keep-sorted start
  "2d",
  "audio",
  "bevy_settings",
  "keyboard",
  "mouse",
  "png",
  "ui",
  "web_asset_cache",
  # keep-sorted end
] }
bevy_resvg.workspace = true
crossbeam-channel = "0.5"
ehttp = "0.7.1"
lightyear = { workspace = true, features = [
  # keep-sorted start
  "avian2d",
  "client",
  "frame_interpolation",
  "input_native",
  "interpolation",
  "metrics",
  "netcode",
  "prediction",
  "replication",
  "std",
  "webtransport",
  # keep-sorted end
] }
log.workspace = true
space-game-game.workspace = true
space-game-protocol.workspace = true
serde_json = "1"
url = "2.5"

[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
space-game-server = { path = "../server" }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
bevy = { workspace = true, features = ["webgpu"] }
bevy_extended_ui = { version = "1.7.0", default-features = false, features = [
  "css-breakpoints",
  "providers",
  "svg",
] }

[target.'cfg(target_family = "wasm")'.dependencies]
bevy = { workspace = true, features = ["webgl2"] }
bevy_extended_ui = { version = "1.7.0", default-features = false, features = [
  "providers",
  "wasm-default",
] }
web-sys = { version = "0.3", features = ["Document", "Location", "Window"] }
