[package]
name = "project-client"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
default = []
dev = ["bevy/dynamic_linking"]

[dependencies]
bevy = { workspace = true, features = [
  # keep-sorted start
  "2d",
  "audio",
  "bevy_settings",
  "keyboard",
  "mouse",
  "ui",
  "web_asset_cache",
  "webgpu",
  # keep-sorted end
] }
bevy_resvg.workspace = true
crossbeam-channel = "0.5"
ehttp = "0.7.1"
lightyear = { workspace = true, features = [
  # keep-sorted start
  "avian2d",
  "client",
  "input_native",
  "interpolation",
  "metrics",
  "netcode",
  "prediction",
  "replication",
  "std",
  "webtransport",
  # keep-sorted end
] }
log.workspace = true
project-game.workspace = true
project-protocol.workspace = true
serde_json = "1"
url = "2.5"

[target.'cfg(target_family = "wasm")'.dependencies]
web-sys = { version = "0.3", features = ["Location", "Window"] }
