[package]
name = "project-protocol"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
bevy.workspace = true
lightyear = { workspace = true, features = [
  # keep-sorted start
  "input_native",
  "interpolation",
  "prediction",
  "replication",
  "std",
  # keep-sorted end
] }
serde.workspace = true
